### PR TITLE
trying to add a linter (codespell and pycodestyle)

### PR DESCRIPTION
**Pull request by fchapoton**
This is just a first sketch. The configuration will certainly needs to be tweaked until the lights come back green.

### CODE REVIEW

**Comment by fchapoton** [comment]
in principle, this is now ready to go. Any opinion ?

**Comment by fchapoton** [comment]
what do you think ? this is working now and should be very harmless.

**Comment by fchapoton** [comment]
now fixed and ready to go ! let's go ?

**Comment by culler** [comment]
@fchapoton can you say a bit about how this will work in practice?  Specifically, will the CI run fail if the linter finds a stylistic error?

**Comment by fchapoton** [comment]
If the linter fails (usually in less than one minute), it will appear in the "Checks" windows as failed. I am not sure wether or not this will stop the rest of the process to happen. I would say no. Should we try ?

**Comment by fchapoton** [comment]
For example, in the similar process run in sagemath/sage, the linter failure does not stop the build and test check.

**Comment by culler** [comment]
Hopefully the linter will produce the full list of all failures in the entire repo before it reports failure.  Is that the case?

**Comment by fchapoton** [comment]
yes, it checks all the repo and reports all failures. But because it has two commands (codespell and pycodestyle), it may stop on the first one it it fails. When refreshing the branch here, I had first to fix codespell warnings, then I got the pycodestyle warnings.

**Comment by fchapoton** [comment]
My plan, once this is activated, is to move on: fix more pycodestyle warnings and add them to the checks. This will go through pull requests, so you will be able to refuse those that you consider controversial.

So can we please merge ?

**Pull request merged**
