### PR TITLE
test no longer for sage 9.1, add test for sage 9.8

### PR DESCRIPTION
**Pull request by fchapoton**
Let us see if everything is fine with the latest sage.

Sage 9.1 is too old now.

### CODE REVIEW

**Comment by fchapoton** [comment]
sadly, sage 9.8 is not yet available on docker hub

**Comment by NathanDunfield** [comment]
@fchapoton First, many thanks for getting updated SageMath docker images created. As I followed that thread in sage-devel, I added 9.8 and 10.0 in 2bcf50ba6c9998d.  Is `ghcr.io/sagemath` now the canonical location for these images?

**Comment by fchapoton** [comment]
hello,
it seems you wrongly added the non-existing 9.10 instead of 10.0.
Concerning the location, I would suggest to stick to dockerhub
so my branch here ismaybe notso pertinent

**Comment by NathanDunfield** [comment]
Thanks for catching the nonexistent 9.10 issue, I feel like the CI should have raised an error there but it didn't.  I have corrected to 10.0, so will close this ticket.

**Comment by NathanDunfield** [comment]
Ugh, I spoke too soon.  I added `10.0`, but GH actions "rounds" this to `10` and then `sagemath/sagemath:10` does not exist.

**Comment by NathanDunfield** [comment]
> Ugh, I spoke too soon. I added `10.0`, but GH actions "rounds" this to `10` and then `sagemath/sagemath:10` does not exist.

I solved this problem after a fashion by referring to 10.0 as `latest`.

**Pull request closed without merging**
