### PR TITLE
refresh the use of sys.version_info (no longer care about python2)

### PR DESCRIPTION
**Pull request by fchapoton**
hopefuly done with enough care :owl:

### CODE REVIEW

**Comment by fchapoton** [comment]
hmm, not sure how my innocuous changes could have broken the CI

**Comment by NathanDunfield** [comment]
> hmm, not sure how my innocuous changes could have broken the CI

Yes, it's definitely not you --- I believe it is this https://github.com/actions/checkout/issues/956.

**Comment by NathanDunfield** [comment]
I fixed the CI issue in master, so if you merge that in all checks should pass.

**Comment by fchapoton** [comment]
green lights, indeed

**Pull request merged**
